name: "microGreen Server"
description: "Automate watering plants"
version: "0.1.0-rc1"
slug: "microgreen-server"
init: false
ingress: true
ingress_port: 1337
ports:
  1337/tcp: 1337
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: mickmister/microgreen-server:0.1.0-rc1
